//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBAMetrics.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public string Id { get; set; }
        public Nullable<bool> Atlanta_Hawks { get; set; }
        public Nullable<bool> Boston_Celtics { get; set; }
        public Nullable<bool> Brooklyn_Nets { get; set; }
        public Nullable<bool> Charlotte_Hornets { get; set; }
        public Nullable<bool> Chicago_Bulls { get; set; }
        public Nullable<bool> Cleveland_Cavaliers { get; set; }
        public Nullable<bool> Dallas_Mavericks { get; set; }
        public Nullable<bool> Denver_Nuggets { get; set; }
        public Nullable<bool> Detroit_Pistons { get; set; }
        public Nullable<bool> Golden_State_Warriors { get; set; }
        public Nullable<bool> Houston_Rockets { get; set; }
        public Nullable<bool> Indiana_Pacers { get; set; }
        public Nullable<bool> LA_Clipers { get; set; }
        public Nullable<bool> Los_Angeles_Lakers { get; set; }
        public Nullable<bool> Memphis_Grizzlies { get; set; }
        public Nullable<bool> Miami_Heat { get; set; }
        public Nullable<bool> Milwaukee_Bucks { get; set; }
        public Nullable<bool> Minnesota_Timberwolves { get; set; }
        public Nullable<bool> New_Orleans_Pelicans { get; set; }
        public Nullable<bool> New_York_Knicks { get; set; }
        public Nullable<bool> Oklahoma_City_Thunder { get; set; }
        public Nullable<bool> Orlando_Magic { get; set; }
        public Nullable<bool> Philadelphia_76ers { get; set; }
        public Nullable<bool> Phoenix_Suns { get; set; }
        public Nullable<bool> Portland_Trail_Blazers { get; set; }
        public Nullable<bool> Sacramento_Kings { get; set; }
        public Nullable<bool> San_Antonio_Spurs { get; set; }
        public Nullable<bool> Toronto_Raptors { get; set; }
        public Nullable<bool> Utah_Jazz { get; set; }
        public Nullable<bool> Washington_Wizards { get; set; }
        public Nullable<bool> Anderson_Packers { get; set; }
        public Nullable<bool> Baltimore_Bullets { get; set; }
        public Nullable<bool> Chicago_Stags { get; set; }
        public Nullable<bool> Cleveland_Rebels { get; set; }
        public Nullable<bool> Detroit_Falcons { get; set; }
        public Nullable<bool> Indianapolis_Jets { get; set; }
        public Nullable<bool> Indianapolis_Olympians { get; set; }
        public Nullable<bool> Pittsburgh_Ironmen { get; set; }
        public Nullable<bool> Providence_Steam_Rollers { get; set; }
        public Nullable<bool> Sheboygan_Red_Skins { get; set; }
        public Nullable<bool> St__Louis_Bombers { get; set; }
        public Nullable<bool> Toronto_Huskies { get; set; }
        public Nullable<bool> Washington_Capitols { get; set; }
        public Nullable<bool> Waterloo_Hawks { get; set; }
    }
}
