//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBAMetrics.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Positions
    {
        public string ID { get; set; }
        public Nullable<int> Atlanta_Hawks { get; set; }
        public Nullable<int> Boston_Celtics { get; set; }
        public Nullable<int> Brooklyn_Nets { get; set; }
        public Nullable<int> Charlotte_Hornets { get; set; }
        public Nullable<int> Chicago_Bulls { get; set; }
        public Nullable<int> Cleveland_Cavaliers { get; set; }
        public Nullable<int> Dallas_Mavericks { get; set; }
        public Nullable<int> Denver_Nuggets { get; set; }
        public Nullable<int> Detroit_Pistons { get; set; }
        public Nullable<int> Golden_State_Warriors { get; set; }
        public Nullable<int> Houston_Rockets { get; set; }
        public Nullable<int> Indiana_Pacers { get; set; }
        public Nullable<int> LA_Clipers { get; set; }
        public Nullable<int> Los_Angeles_Lakers { get; set; }
        public Nullable<int> Memphis_Grizzlies { get; set; }
        public Nullable<int> Miami_Heat { get; set; }
        public Nullable<int> Milwaukee_Bucks { get; set; }
        public Nullable<int> Minnesota_Timberwolves { get; set; }
        public Nullable<int> New_Orleans_Pelicans { get; set; }
        public Nullable<int> New_York_Knicks { get; set; }
        public Nullable<int> Oklahoma_City_Thunder { get; set; }
        public Nullable<int> Orlando_Magic { get; set; }
        public Nullable<int> Philadelphia_76ers { get; set; }
        public Nullable<int> Phoenix_Suns { get; set; }
        public Nullable<int> Portland_Trail_Blazers { get; set; }
        public Nullable<int> Sacramento_Kings { get; set; }
        public Nullable<int> San_Antonio_Spurs { get; set; }
        public Nullable<int> Toronto_Raptors { get; set; }
        public Nullable<int> Utah_Jazz { get; set; }
        public Nullable<int> Washington_Wizards { get; set; }
        public Nullable<int> Anderson_Packers { get; set; }
        public Nullable<int> Baltimore_Bullets { get; set; }
        public Nullable<int> Chicago_Stags { get; set; }
        public Nullable<int> Cleveland_Rebels { get; set; }
        public Nullable<int> Detroit_Falcons { get; set; }
        public Nullable<int> Indianapolis_Jets { get; set; }
        public Nullable<int> Indianapolis_Olympians { get; set; }
        public Nullable<int> Pittsburgh_Ironmen { get; set; }
        public Nullable<int> Providence_Steam_Rollers { get; set; }
        public Nullable<int> Sheboygan_Red_Skins { get; set; }
        public Nullable<int> St__Louis_Bombers { get; set; }
        public Nullable<int> Toronto_Huskies { get; set; }
        public Nullable<int> Washington_Capitols { get; set; }
        public Nullable<int> Waterloo_Hawks { get; set; }
    }
}
